### ISSUE TITLE
Fix breaking tests related to Gatsby `<Link>`, e.g. `MainNavigation`

### ISSUE THREAD

**Issue by S-unya** [aerian-studios/aerian-site-rebuild#48]
It seems that Gatsby Link component breaks tests and storybooks with the following error:

```
Cannot find module './pages.json' from 'public-page-renderer-dev.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:210:17)
      at Object.<anonymous> (node_modules/gatsby/cache-dir/public-page-renderer-dev.js:12:37)
```

**Comment by ascorbic** [comment]
Fixed in 9aec0dac2e2b8eab2f5a19d456928d40a6810885
